---
- name: Create project for Gluster recycler
  openshift_project:
    name: "{{ appuio_gluster_recycler_namespace }}"

- name: Add gluster-recycler service account to privileged scc
  openshift_policy:
    sccs:
      - privileged
    users:
      - "system:serviceaccount:{{ appuio_gluster_recycler_namespace }}:gluster-recycler"

- name: Create temp directory for doing work in
  tempfile:
    state: directory
  register: tempdir
  changed_when: False

- block:
    - name: Copy template
      with_list:
        - recycler-build.yml
        - recycler-template.yml
      copy:
        src: "{{ role_path }}/files/{{ item }}"
        dest: "{{ tempdir.path }}/{{ item }}"
      changed_when: False

    - name: Instantiate base recycler template
      openshift_resource:
        namespace: "{{ appuio_gluster_recycler_namespace }}"
        template: "{{ tempdir.path }}/recycler-build.yml"
        app_name: gluster-recycler
        arguments:
          BASE_IMAGE: "{{ appuio_gluster_recycler_base_image }}"
          SOURCE_REPO: "{{ appuio_gluster_recycler_repo }}"
          SOURCE_REF: "{{ appuio_gluster_recycler_repo_rev }}"

    - name: Instantiate main recycler template
      openshift_resource:
        namespace: "{{ appuio_gluster_recycler_namespace }}"
        template: "{{ tempdir.path }}/recycler-template.yml"
        app_name: gluster-recycler
        arguments:
          NAMESPACE: "{{ appuio_gluster_recycler_namespace }}"
          GLUSTER_HOSTS: "{{ appuio_gluster_recycler_gluster_hosts | mandatory }}"
          INTERVAL: "{{ appuio_gluster_recycler_interval_seconds | string }}"
          DELAY: "{{ appuio_gluster_recycler_delay_seconds | string }}"
          TIMEZONE: "{{ appuio_gluster_recycler_timezone }}"
  always:
    - name: Delete temp directory
      file:
        name: "{{ tempdir.path }}"
        state: absent
      changed_when: False
