---
- name: Create project for Gluster recycler
  openshift_project:
    name: "{{ appuio_gluster_recycler_namespace }}"

- name: Add gluster-recycler service account to privileged scc
  openshift_policy:
    sccs:
      - privileged
    users:
      - "system:serviceaccount:{{ appuio_gluster_recycler_namespace }}:gluster-recycler"

- name: Instantiate recycler template
  openshift_resource:
    namespace: "{{ appuio_gluster_recycler_namespace }}"
    template: "{{ role_path }}/files/recycler-template.yml"
    app_name: gluster-recycler
    arguments:
      NAMESPACE: "{{ appuio_gluster_recycler_namespace }}"
      GLUSTER_HOSTS: "{{ appuio_gluster_recycler_gluster_hosts | mandatory }}"
      BASE_IMAGE: "{{ appuio_gluster_recycler_base_image }}"
      SOURCE_REPO: "{{ appuio_gluster_recycler_repo }}"
      SOURCE_REF: "{{ appuio_gluster_recycler_repo_rev }}"
      INTERVAL: "{{ appuio_gluster_recycler_interval_seconds | string }}"
      DELAY: "{{ appuio_gluster_recycler_delay_seconds | string }}"
      TIMEZONE: "{{ appuio_gluster_recycler_timezone }}"
