---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Setup for GlusterFS persistent volume recycler
    version: '1.0.0'
  name: setup-recycler
labels:
  template: "gluster-recycler"
parameters:
- description: 'The name of the namespace being deployed into (sorry, templates cant look this up)'
  name: NAMESPACE
  required: true
- description: 'A semi-colon ";" separated list of glusterfs hosts that make up your glusterfs cluster (only one cluster supported).'
  name: GLUSTER_HOSTS
  required: true
- description: 'Cronjob execution schedule in cron format'
  name: SCHEDULE
  required: false
  value: "*/5 * * * *"
- description: 'Delay in seconds before a volume is recycled after it failed (defaults to no delay)'
  name: DELAY
  required: false
  value: "0"
- description: 'Enable extra logging for debugging (defaults to false)'
  name: DEBUG
  required: false
  value: "false"
- description: 'Timezone (TZ) of the container, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list'
  name: TIMEZONE
  value: UTC
  required: true
- description: 'Name of image stream for recycler container'
  name: IMAGE_STREAM_NAME
  value: gluster-recycler
  required: true
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: gluster-recycler

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: gluster-recycler
  rules:
  - verbs:
    - create
    - delete
    - get
    - list
    - replace
    - update
    - patch
    attributeRestrictions:
    apiGroups:
    resources:
    - persistentvolumes

- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    name: gluster-recycler
  roleRef:
    name: gluster-recycler
  subjects:
  - kind: ServiceAccount
    name: gluster-recycler
    namespace: ${NAMESPACE}
  userNames:
  - system:serviceaccount:${NAMESPACE}:gluster-recycler

- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: gluster-recycler
    annotations:
      # https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#image-stream-kubernetes-resources
      image.openshift.io/triggers: |-
        [{
          "from": {
            "kind": "ImageStreamTag",
            "name": "${IMAGE_STREAM_NAME}:latest"
          },
          "fieldPath": "spec.jobTemplate.spec.template.spec.containers[?(@.name==\"gluster-recycler\")].image"
        }]
  spec:
    schedule: ${SCHEDULE}
    failedJobsHistoryLimit: 10
    successfulJobsHistoryLimit: 10
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        activeDeadlineSeconds: 7200
        completions: 1
        # Don't retry failed executions
        backoffLimit: 0
        template:
          metadata:
            labels:
              name: gluster-recycler
          spec:
            containers:
            - name: gluster-recycler
              image: " "
              imagePullPolicy: IfNotPresent
              env:
              - name: ONESHOT
                value: "true"
              - name: DELAY
                value: ${DELAY}
              - name: CLUSTER
                value: ${GLUSTER_HOSTS}
              - name: DEBUG
                value: ${DEBUG}
              - name: TZ
                value: ${TIMEZONE}
              args:
                - "bash"
                - "-c"
                - "/recycler.sh"
              securityContext:
                privileged: true
            serviceAccountName: gluster-recycler
            # https://github.com/kubernetes/kubernetes/issues/54870
            restartPolicy: Never
