---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: "Setup for glusterfs persistent volume recycler.  Creates all the required objects and deploys the pod."
    version: '1.0.0'
  name: setup-recycler
labels:
  template: "gluster-recycler"
parameters:
- description: 'The name of the namespace being deployed into (sorry, templates cant look this up)'
  name: NAMESPACE
  required: true
- description: 'A semi-colon ";" separated list of glusterfs hosts that make up your glusterfs cluster (only one cluster supported).'
  name: GLUSTER_HOSTS
  required: true
- description: 'Interval in seconds between recycler runs (defaults to every 5 minutes)'
  name: INTERVAL
  required: false
  value: "300"
- description: 'Delay in seconds before a volume is recycled after it failed (defaults to no delay)'
  name: DELAY
  required: false
  value: "0"
- description: 'Enable extra logging for debugging (defaults to false)'
  name: DEBUG
  required: false
  value: "false"
- description: Base image for recycler, registry.access.redhat.com/rhel7 or docker.io/library/centos:7, defaults to the former
  name: BASE_IMAGE
  required: true
  value: registry.access.redhat.com/rhel7
- description: 'Source Repo for recycler'
  name: SOURCE_REPO
  required: true
  value: "https://github.com/appuio/gluster-recycler.git"
- description: 'Gluster recycler version, i.e. git ref of the specified repository'
  name: SOURCE_REF
  value: master
  required: true
- description: 'Timezone (TZ) of the container, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list'
  name: TIMEZONE
  value: UTC
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: gluster-recycler-base
  spec:
    tags:
      - name: latest
        from:
          kind: DockerImage
          name: ${BASE_IMAGE}
        importPolicy:
          scheduled: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: gluster-recycler
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: gluster-recycler
- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: gluster-recycler
  rules:
  - verbs:
    - create
    - delete
    - get
    - list
    - replace
    - update
    - patch
    attributeRestrictions:
    apiGroups:
    resources:
    - persistentvolumes
- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    name: gluster-recycler
  roleRef:
    name: gluster-recycler
  subjects:
  - kind: ServiceAccount
    name: gluster-recycler
    namespace: ${NAMESPACE}
  userNames:
  - system:serviceaccount:${NAMESPACE}:gluster-recycler
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: gluster-recycler
    name: gluster-recycler
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: gluster-recycler:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPO}
        ref: ${SOURCE_REF}
      secrets: []
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: gluster-recycler-base:latest
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
    name: gluster-recycler
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      name: gluster-recycler
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: gluster-recycler
        name: gluster-recycler
      spec:
        containers:
        - name: gluster-recycler
          image: gluster-recycler
          imagePullPolicy: Always
          env:
          - name: INTERVAL
            value: ${INTERVAL}
          - name: DELAY
            value: ${DELAY}
          - name: CLUSTER
            value: ${GLUSTER_HOSTS}
          - name: DEBUG
            value: ${DEBUG}
          - name: TZ
            value: ${TIMEZONE}
          args:
            - "bash"
            - "-c"
            - "/recycler.sh"
          securityContext:
            privileged: true
        restartPolicy: Always
        serviceAccountName: gluster-recycler
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        from:
          kind: ImageStream
          name: gluster-recycler
        containerNames:
        - gluster-recycler
