---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Cron job for GlusterFS persistent volume recycler
    version: '1.0.0'
labels:
  template: "gluster-recycler"
parameters:
- description: >-
    A semi-colon separated list of GlusterFS volume file servers; if not specified the endpoint
    object named in the persistent volume object is retrieved from the recycler pod namespace
  name: GLUSTER_HOSTS
- description: 'Cronjob execution schedule in cron format'
  name: SCHEDULE
  required: false
  value: "*/5 * * * *"
- description: 'Delay in seconds before a volume is recycled after it failed (defaults to no delay)'
  name: DELAY
  required: false
  value: "0"
- description: 'Enable extra logging for debugging (defaults to false)'
  name: DEBUG
  required: false
  value: "false"
- description: 'Timezone (TZ) of the container, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list'
  name: TIMEZONE
  value: UTC
  required: true
- description: 'Name of image stream for recycler container'
  name: IMAGE_STREAM_NAME
  value: gluster-recycler
  required: true
- description: Node selector for recycler pod in JSON format
  name: NODE_SELECTOR_JSON
  value: "{}"
- description: "Docker image to use (overwritten by trigger)"
  name: IMAGE
  value: " "
objects:

- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: gluster-recycler
    annotations:
      # https://docs.openshift.com/container-platform/3.9/dev_guide/managing_images.html#image-stream-kubernetes-resources
      image.openshift.io/triggers: |-
        [{
          "from": {
            "kind": "ImageStreamTag",
            "name": "${IMAGE_STREAM_NAME}:latest"
          },
          "fieldPath": "spec.jobTemplate.spec.template.spec.containers[?(@.name==\"gluster-recycler\")].image"
        }]
  spec:
    schedule: ${SCHEDULE}
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 86400
    jobTemplate:
      spec:
        activeDeadlineSeconds: 7200
        completions: 1
        # Don't retry failed executions
        backoffLimit: 0
        template:
          metadata:
            labels:
              name: gluster-recycler
          spec:
            containers:
            - name: gluster-recycler
              image: ${IMAGE}
              imagePullPolicy: IfNotPresent
              env:
              - name: ONESHOT
                value: "true"
              - name: DELAY
                value: ${DELAY}
              - name: CLUSTER
                value: ${GLUSTER_HOSTS}
              - name: DEBUG
                value: ${DEBUG}
              - name: TZ
                value: ${TIMEZONE}
              - name: GLUSTER_OBJECT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              args: []
              securityContext:
                privileged: true
              volumeMounts:
                - name: secrets
                  mountPath: /recycler-secrets
                  readOnly: true
            serviceAccountName: gluster-recycler
            restartPolicy: Never
            nodeSelector: ${{NODE_SELECTOR_JSON}}
            volumes:
              - name: secrets
                secret:
                  defaultMode: 400
                  secretName: gluster-recycler
