---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Setup for GlusterFS persistent volume recycler
    version: '1.0.0'
  name: setup-recycler
labels:
  template: "gluster-recycler"
parameters:
- description: 'The name of the namespace being deployed into (sorry, templates cant look this up)'
  name: NAMESPACE
  required: true
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: gluster-recycler

- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: gluster-recycler
  rules:
  - verbs:
    - create
    - delete
    - get
    - list
    - replace
    - update
    - patch
    attributeRestrictions:
    apiGroups:
    resources:
    - persistentvolumes
  - verbs:
    - get
    attributeRestrictions:
    apiGroups:
    resources:
    - endpoints

- apiVersion: v1
  kind: Secret
  metadata:
    name: gluster-recycler
  data: {}

- apiVersion: v1
  groupNames: null
  kind: ClusterRoleBinding
  metadata:
    name: gluster-recycler
  roleRef:
    name: gluster-recycler
  subjects:
  - kind: ServiceAccount
    name: gluster-recycler
    namespace: ${NAMESPACE}
  userNames:
  - system:serviceaccount:${NAMESPACE}:gluster-recycler
